### ISSUE TITLE
Better Markdown support in Shiny buildpack

### ISSUE THREAD

**Issue by doprdele** [hmdc/heroku-shiny-demo#3]
# Problem
Markdown files are not pre-compiled properly for Shiny. The Shiny buildpack should pre-compile "R Markdown" such that the Markdown is not recompiled upon initial HTTP request, resulting in out of memory errors.

# Solution
Make sure R Markdown files are pre-compiled and served from cache

**Comment by mreekie** [comment]
will essentially look for rmd language and run the compiler against them at build time.

**Comment by mreekie** [comment]
We sized this at 5 story points

**Comment by doprdele** [comment]
Two problems exist:

1) Pandoc was not properly rendering HTML files because it was writing to an inexistant directory /tmp. Heroku Dynos do not have /tmp directory. I needed to set the ```intermediate_dir``` on the ```rmarkdown::render``` function.

```
rmarkdown::run(dir = getwd(),
               render_args = list(output_dir = ".",
                                  intermediates_dir = "."),
               shiny_args = list(host = "127.0.0.1",
                                 port = as.numeric(port)))
```

2) Still, rmarkdown is returning 'exited with code 1', while actually working sometimes. Reason unknown. 1/2 fixed.

**Comment by mreekie** [comment]
This is is as done as it's going to get.   CLosing.
Any further work is being done via
Replace R-Shiny build pack implementation with a container based implemenation #4
